rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head

matrix:
  include:
    - rvm: 1.9.3
      env: ICU_VERSION=4.2.1
    - rvm: 1.9.3
      env: ICU_VERSION=54.1
    - rvm: 2.1
      env: ICU_VERSION=4.2.1
    - rvm: 2.1
      env: ICU_VERSION=54.1
    - rvm: 2.1
      env: WITH_DEV_PACKAGE=1
  allow_failures:
    - rvm: ruby-head

before_install:
  - >
    test -z "$ICU_VERSION" || (
      curl -L "https://downloads.sourceforge.net/project/icu/ICU4C/$ICU_VERSION/icu4c-$(echo $ICU_VERSION | tr . _)-src.tgz" | tar xz
      mkdir icu/build
      cd icu/source
      ./runConfigureICU Linux --disable-extras --disable-samples --disable-tests --prefix="$(dirname $(pwd))/build"
      make --quiet
      make --quiet install
    )
  - test -n "$ICU_VERSION" || test -z "$WITH_DEV_PACKAGE" || sudo apt-get install libicu-dev
  - test -n "$ICU_VERSION" || test -n "$WITH_DEV_PACKAGE" || sudo apt-get install ^libicu..$

script: >
  if [ "$ICU_VERSION" ] ; then
    ICU_DIR="$(pwd)/icu/build" LD_LIBRARY_PATH="$(pwd)/icu/build/lib" rake
  else
    rake
  fi
