rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head

matrix:
  include:
    - rvm: 1.9.3
      env: ICU_VERSION=4.2.1
    - rvm: 1.9.3
      env: ICU_VERSION=54.1
    - rvm: 2.1
      env: ICU_VERSION=4.2.1
    - rvm: 2.1
      env: ICU_VERSION=54.1
    - rvm: 2.1
      env: WITH_DEV_PACKAGE=1
  allow_failures:
    - rvm: ruby-head

before_install: ./.travis.sh before_install
