rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

matrix:
  include:
    - rvm: 1.9.3
      env: ICU_VERSION=4.2.1
    - rvm: 1.9.3
      env: ICU_VERSION=53.1
    - rvm: 2.1.0
      env: ICU_VERSION=4.2.1
    - rvm: 2.1.0
      env: ICU_VERSION=53.1

before_install:
  - test -n "$ICU_VERSION" || sudo apt-get install libicu-dev
  - >
    test -z "$ICU_VERSION" || (
      curl "http://download.icu-project.org/files/icu4c/$ICU_VERSION/icu4c-$(echo $ICU_VERSION | tr . _)-src.tgz" | tar xz
      mkdir icu/build
      cd icu/source
      ./runConfigureICU Linux --disable-extras --disable-samples --disable-tests --prefix="$(dirname $(pwd))/build"
      make --quiet
      make --quiet install
    )

script: >
  if [ "$ICU_VERSION" ] ; then
    LD_LIBRARY_PATH="$(pwd)/icu/build/lib" rake -- --with-icu-dir="$(pwd)/icu/build"
  else
    rake
  fi
